### ISSUE TITLE
Version 3.0 256GB

### ISSUE THREAD

**Issue by FSSERRA** [MagicXHandheld/XU10#10]
**when will the 256gb version of version 3.0 be available?**

**Comment by MagicXHandheld** [comment]
updated~

**Comment by markdinh** [comment]
Hmm, the torrent only goes up to the .015 archive part for me and is 73gb instead of larger.  Seems like the torrent file is corrupt?

**Comment by WhyGB** [comment]
The same for the 3.0 128 gb. Torrent only goes up to 015 part (should have 22)

**Comment by MagicXHandheld** [comment]
It is recommended to download them one by one instead of using Torrent. I don’t know why Torrent behaves like this. Maybe you can tell me which platform is better for uploading.

**Comment by markdinh** [comment]
I did download one by one (after 15) and it worked just fine. Thank you!
