### ISSUE TITLE
Unzip Files, create on file image - Which Tool?

### ISSUE THREAD

**Issue by iOF79** [MagicXHandheld/XU10#12]
Hello Friends,

the SD Card from my XU10 died for no reason so I need a new. I tried severall Versions of these but all won´t work with what I am trying. I am using 7zip on Windows 10 and it always says: Dataerror after decompression first Image (001)

What tools do you use to success creating a one file image?

I miss my XGameBoy10 :(

**Comment by YozenPL** [comment]
You need to download all files 001, 002, 003 etc.
One you have ALL of them just unzip the .001, and it will use all files to create the *.img.gz file.

**Comment by iOF79** [comment]
Thanx

That's what I did and no success. Which Unzip Program do you use?

**Comment by YozenPL** [comment]
7-zip to unpack.
Win32DiskImager to write *.img to sd card.

**Comment by MagicXHandheld** [comment]
或许你下载的文件损坏,请仔细看一下具体的字节大小，对比下载的文件,下次上传我将生成MD5码

**Comment by Dbailon** [comment]
Hi @iOF79, have you tried to close Torrent while burning the image in your card?

**Comment by iOF79** [comment]
hallo friends

I have tried to download 64 GB, 128 gb Version 2 and version 3. For example the 128GB Files have all the exact same size but always Dara Error after IMG 001. An Idea could be that the final file name is not supported cause it has some strange symbols. I cannot change the final image name so I can't test that. I can download again but have no hope it'll work this time. All downloads were successful last time

**Comment by MagicXHandheld** [comment]
> 你好朋友们
> 
> 我尝试下载 64 GB、128 GB 版本 2 和版本 3。例如，128GB 文件大小完全相同，但 IMG 001 之后总是出现 Dara 错误。一个想法可能是最终文件名不受支持，因为它有一些奇怪的符号。我无法更改最终图像名称，所以我无法测试。我可以再次下载，但这次不指望它会成功。上次所有下载都成功了

Can you take a screenshot of the downloaded file?

**Comment by iOF79** [comment]
![image](https://github.com/MagicXHandheld/XU10/assets/161466403/e971e353-f45a-4616-90fb-f7a72fd9189d)

**Comment by iOF79** [comment]
![image](https://github.com/MagicXHandheld/XU10/assets/161466403/94b9726e-9cf2-49fa-8b1c-6eed016c64ff)

**Comment by MagicXHandheld** [comment]
I think I know what the problem is. The IMG that should be decompressed has Chinese characters. I will pay attention to it next time I upload it.

**Comment by iOF79** [comment]
Thank you your attention and answere...

But some other user succeeded! Maybe I change windows language? How did they succeed?

**Comment by MagicXHandheld** [comment]
I don't know how to solve it at the moment. You can only wait for me to upload it again.

**Comment by iOF79** [comment]
UPDATE

I had to reinstall Windows cause of a full disk. Now with Version 3.2 everything is working perfectly! Thank you so much

issue can be closed
