### ISSUE TITLE
Problem with version 3.2 iso

### ISSUE THREAD

**Issue by Sutolix** [MagicXHandheld/XU10#17]
I tried to update to version 3.2 64GB downloaded via torrent and balenaEtcher failed to validate the files. I tried using other software to burn the ISO to my SD card and they also failed. I went back to version 3.0 and everything worked perfectly so I don't think it's a problem with my SD card or the software I'm using. I haven't tested the 128GB and 256GB ISOs.

**Comment by Dbailon** [comment]
I had no problem burning and playing the 3.2. Make sure to close your Torrent client so the file is not being used while burning. It failed for me previously because of that.

**Comment by Sutolix** [comment]
Hi, I'll try

**Comment by Sutolix** [comment]
I tested it again, this time using a non-torrent download manager and it worked, thanks
