### ISSUE TITLE
Anomalia com o cartão? consola está constantemente a reiniciar

### ISSUE THREAD

**Issue by Pegassos1976** [MagicXHandheld/XU10#4]
Boa noite, 
Quando ligo a consola ela começou a reiniciar de forma automática e repetidamente, não chegando ao ecrã de opções e por isso não sei o que fazer?
Alguém com o mesmo problema?

**Comment by MagicXHandheld** [comment]
I tried to translate your message but I don't understand Portuguese.
Depending on your problem, you may need to re-download the latest firmware, which I updated recently.

**Comment by Pegassos1976** [comment]
How Do I Make It?

**Comment by MagicXHandheld** [comment]
My suggestion is that you re-download the firmware corresponding to your TF card, re-burn it and try it again.
