### ISSUE TITLE
XU10 boot error after replacing new SD card

### ISSUE THREAD

**Issue by St4rscr34m-1981** [MagicXHandheld/XU10#5]
![Error_XU10](https://github.com/MagicXHandheld/XU10/assets/84049738/650074e5-1988-415b-a1f2-bb96ec2cd93b)

Hello my friend,

I'm trying to replace the SD card that came with my XU10 by downloading it from the repository and installing JelOS on a 64GB Lexar card and whenever I start it after it's ready it shows this error on the screen. I've tried with another 128GB Lexar card but the same error occurs. 

Could you help me resolve this?

**Comment by MagicXHandheld** [comment]
Now updated to 3.0, the problem has been fixed.
