### ISSUE TITLE
BUG torrent link of all sizes only contains 64GB size

### ISSUE THREAD

**Issue by Gustavo98GTO** [MagicXHandheld/XU10#6]
Hello, I downloaded the 256GB version, however, when I installed it, it appeared that the file had a problem, so I deleted the file and tried to download the torrent version, but the torrent that appears in the links folder of the 256GB file, only contains the 64Gb update. I tried the basic method with the 164gb one but also without success when trying to install and coincidentally the torrent from the 128gb link only downloads the 64gb file, even though the name of the torrent file is correct, the size of the files (256 and 128) is 64GB

**Comment by MagicXHandheld** [comment]
This 3.0 update, you can try it again. There should be no problem

**Comment by WhyGB** [comment]
I downloaded the torrent file for 3.0 128gb found in the link. The torrent only seemed to have gz files 001-015
It looks like it needs additional files 016-022 for the disk image to be created.

**Comment by MagicXHandheld** [comment]
It is recommended to download them one by one instead of using Torrent. I don’t know why Torrent behaves like this. Maybe you can tell me which platform is better for uploading.

**Comment by WhyGB** [comment]
For the 128gb, I ended up using the torrent for files 1-15 and downloaded the rest individually from the archive. It worked great.
